#!/bin/bash
# =============================================================================
# Vault Enterprise — cloud-init bootstrap
# Cluster : ${cluster_name}
# Region  : ${aws_region}
# =============================================================================
# Template variables (injected by Terraform templatefile):
#   cluster_name, vault_version, vault_license, kms_key_id,
#   aws_region, ssm_prefix, vault_api_addr
# =============================================================================
set -euo pipefail

# ─── Redirect all output to a persistent log ─────────────────────────────────
exec > >(tee -a /var/log/vault-cloud-init.log) 2>&1

log() { echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] $*"; }

log "=== Vault cloud-init starting (cluster: ${cluster_name}) ==="

# ─── Terraform-injected values ───────────────────────────────────────────────
VAULT_VERSION="${vault_version}"
VAULT_LICENSE="${vault_license}"
KMS_KEY_ID="${kms_key_id}"
AWS_REGION="${aws_region}"
SSM_PREFIX="${ssm_prefix}"
VAULT_API_ADDR="${vault_api_addr}"

# ─── System packages ─────────────────────────────────────────────────────────
log "Installing system packages..."
dnf update -y -q
dnf install -y -q docker jq openssl

systemctl enable --now docker
log "Docker started: $(docker --version)"

# ─── IMDSv2 — get private IP ─────────────────────────────────────────────────
log "Fetching instance metadata..."
IMDS_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 300")
PRIVATE_IP=$(curl -s -H "X-aws-ec2-metadata-token: $IMDS_TOKEN" \
  "http://169.254.169.254/latest/meta-data/local-ipv4")
log "Private IP: $PRIVATE_IP  |  Public IP (EIP): $VAULT_API_ADDR"

# ─── Directory layout ────────────────────────────────────────────────────────
log "Creating Vault directory layout..."
mkdir -p /opt/vault/{config,data,certs,logs}
# Vault container runs as UID 100 (vault user) — all writable paths must be owned by 100:1000
chown -R 100:1000 /opt/vault/data /opt/vault/certs
chmod 755 /opt/vault/data /opt/vault/{config,certs,logs}

# ─── Self-signed TLS certificate ─────────────────────────────────────────────
log "Generating self-signed TLS certificate (valid 10 years)..."
cat > /tmp/vault-openssl.cnf <<SSLCNF
[req]
default_bits       = 4096
prompt             = no
default_md         = sha256
distinguished_name = dn
x509_extensions    = v3_req

[dn]
CN = vault.${cluster_name}

[v3_req]
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints       = critical, CA:FALSE
keyUsage               = critical, digitalSignature, keyEncipherment
extendedKeyUsage       = serverAuth
subjectAltName         = @alt_names

[alt_names]
IP.1  = $VAULT_API_ADDR
IP.2  = $PRIVATE_IP
IP.3  = 127.0.0.1
DNS.1 = vault.${cluster_name}
DNS.2 = vault.local
SSLCNF

openssl req -x509 -newkey rsa:4096 \
  -keyout /opt/vault/certs/vault.key \
  -out    /opt/vault/certs/vault.crt \
  -days 3650 -nodes \
  -config /tmp/vault-openssl.cnf

chmod 644 /opt/vault/certs/vault.crt
chmod 640 /opt/vault/certs/vault.key   # vault user (UID 100) owns this via group 1000
chown 100:1000 /opt/vault/certs/vault.crt /opt/vault/certs/vault.key
rm -f /tmp/vault-openssl.cnf
log "TLS certificate written to /opt/vault/certs/"

# ─── Vault configuration ─────────────────────────────────────────────────────
log "Writing Vault configuration..."
cat > /opt/vault/config/vault.hcl <<VAULTCFG
# Vault Enterprise — single-node Raft cluster
# Generated by cloud-init on $(date -u '+%Y-%m-%dT%H:%M:%SZ')

ui            = true
disable_mlock = true
log_level     = "info"
log_format    = "json"

api_addr     = "https://$VAULT_API_ADDR:8200"
cluster_addr = "https://$PRIVATE_IP:8201"

listener "tcp" {
  address         = "0.0.0.0:8200"
  tls_cert_file   = "/vault/certs/vault.crt"
  tls_key_file    = "/vault/certs/vault.key"
  tls_min_version = "tls12"
}

storage "raft" {
  path    = "/vault/data"
  node_id = "vault-node-1"
}

seal "awskms" {
  region     = "$AWS_REGION"
  kms_key_id = "$KMS_KEY_ID"
}
VAULTCFG

log "Vault configuration written."

# ─── Start Vault container ───────────────────────────────────────────────────
# Notes:
#   --user 100:1000          : run as vault user (matches volume ownership set above)
#   --entrypoint /bin/vault  : bypass the image's docker-entrypoint.sh which fails
#                              to set CAP_SETFCAP on EC2; we handle permissions above
#   No --cap-add IPC_LOCK    : disable_mlock = true in vault.hcl makes this unnecessary
log "Starting Vault Enterprise container (version: $VAULT_VERSION)..."

docker run -d \
  --name vault \
  --restart unless-stopped \
  --user 100:1000 \
  --entrypoint /bin/vault \
  -p 8200:8200 \
  -p 8201:8201 \
  -e VAULT_LICENSE="$VAULT_LICENSE" \
  --log-opt max-size=100m \
  --log-opt max-file=3 \
  -v /opt/vault/config:/vault/config:ro \
  -v /opt/vault/data:/vault/data \
  -v /opt/vault/certs:/vault/certs:ro \
  "hashicorp/vault-enterprise:$VAULT_VERSION" \
  server -config=/vault/config/vault.hcl

log "Vault container started. Waiting for API to become available..."

# ─── Wait for Vault API ───────────────────────────────────────────────────────
# HTTP 501 = uninitialized (expected here); 200/429 = initialized+unsealed/sealed
MAX_WAIT=60
for attempt in $(seq 1 $MAX_WAIT); do
  HTTP_STATUS=$(curl -sk -o /dev/null -w "%%{http_code}" \
    "https://127.0.0.1:8200/v1/sys/health" 2>/dev/null || echo "000")

  case "$HTTP_STATUS" in
    200|429|472|473|501)
      log "Vault API responding — HTTP $HTTP_STATUS (attempt $attempt)"
      break
      ;;
    *)
      log "Attempt $attempt/$MAX_WAIT — HTTP $HTTP_STATUS, retrying in 5s..."
      sleep 5
      ;;
  esac

  if [ "$attempt" -eq "$MAX_WAIT" ]; then
    log "ERROR: Vault did not become ready after $((MAX_WAIT * 5))s. Dumping container logs:"
    docker logs vault --tail 50
    exit 1
  fi
done

# ─── Initialize Vault ────────────────────────────────────────────────────────
INIT_STATUS=$(curl -sk "https://127.0.0.1:8200/v1/sys/init" | jq -r '.initialized')

if [ "$INIT_STATUS" = "false" ]; then
  log "Vault is not yet initialized — running 'vault operator init'..."

  INIT_JSON=$(docker exec \
    -e VAULT_ADDR="https://127.0.0.1:8200" \
    -e VAULT_SKIP_VERIFY="true" \
    vault \
    vault operator init \
      -recovery-shares=5 \
      -recovery-threshold=3 \
      -format=json)

  ROOT_TOKEN=$(echo "$INIT_JSON" | jq -r '.root_token')

  # ─── Store secrets in SSM Parameter Store ──────────────────────────────────
  log "Storing root token in SSM: $SSM_PREFIX/root_token"
  aws ssm put-parameter \
    --region "$AWS_REGION" \
    --name "$SSM_PREFIX/root_token" \
    --description "Vault root token — ${cluster_name}" \
    --value "$ROOT_TOKEN" \
    --type "SecureString" \
    --overwrite

  log "Storing recovery keys in SSM..."
  for i in 0 1 2 3 4; do
    KEY=$(echo "$INIT_JSON" | jq -r ".recovery_keys_b64[$i] // empty")
    [ -z "$KEY" ] && continue
    aws ssm put-parameter \
      --region "$AWS_REGION" \
      --name "$SSM_PREFIX/recovery_key_$((i + 1))" \
      --description "Vault recovery key $((i + 1)) — ${cluster_name}" \
      --value "$KEY" \
      --type "SecureString" \
      --overwrite
    log "  recovery_key_$((i + 1)) stored."
  done

  # Clear sensitive data from shell memory
  unset ROOT_TOKEN INIT_JSON

  log "=== Vault initialized successfully. Secrets stored in SSM under $SSM_PREFIX/ ==="
else
  log "Vault is already initialized — skipping init."
fi

log "=== Vault cloud-init complete ==="
log "    UI  : https://$VAULT_API_ADDR:8200/ui"
log "    Root token  : aws ssm get-parameter --name '$SSM_PREFIX/root_token' --with-decryption --region $AWS_REGION"
log "    TLS cert    : /opt/vault/certs/vault.crt  (copy to client as VAULT_CACERT)"
