# ─── Vault Connection ──────────────────────────────────────────────────────

variable "vault_addr" {
  description = "Address of the Vault server. Used for TFE workspace variable injection."
  type        = string
}

variable "vault_token" {
  description = "Vault token used to authenticate the Vault provider. Bootstrap with a root token; rotate to a scoped token for ongoing use."
  type        = string
  sensitive   = true
}

variable "vault_ca_cert_file" {
  description = "Path to a PEM-encoded CA certificate file for Vault TLS verification. Leave empty to use system CAs or set VAULT_CACERT instead."
  type        = string
  default     = ""
}

variable "vault_namespace" {
  description = "Vault namespace. Leave empty for root namespace."
  type        = string
  default     = ""
}

# ─── TFE Identity ──────────────────────────────────────────────────────────

variable "tfe_hostname" {
  description = "Hostname of the self-hosted Terraform Enterprise instance."
  type        = string
}

variable "tfe_token" {
  description = "TFE API token with permission to manage workspace variables. Required when setting up workspace variable injection."
  type        = string
  sensitive   = true
  default     = ""
}

variable "tfe_organization" {
  description = "TFE organization name used to scope JWT bound_claims."
  type        = string
}

variable "tfe_project" {
  description = "TFE project name used to scope JWT bound_claims.. Use '*' to match all projects."
  type        = string
  default     = "*"
}

variable "tfe_workspace" {
  description = "TFE workspace name used to scope JWT bound_claims. Use '*' to match all workspaces in the project."
  type        = string
  default     = "*"
}

# ─── Vault JWT Auth Backend ────────────────────────────────────────────────

variable "jwt_backend_path" {
  description = "Mount path for the JWT auth backend. Must be unique within the Vault instance; use a distinct value when deploying alongside dynamic_vault_secrets."
  type        = string
  default     = "jwt-aws-provider"
}

variable "vault_role_name" {
  description = "Name of the Vault JWT auth role for TFE workspaces."
  type        = string
  default     = "tfe-vault-backed-aws"
}

variable "workload_identity_audience" {
  description = "Expected 'aud' claim in TFE workload identity tokens. Must be different from other JWT backends to avoid authentication conflicts. Default is specific to AWS provider credentials flow."
  type        = string
  default     = "vault.workload.identity.aws"
}

variable "token_ttl_seconds" {
  description = "Lifetime in seconds for Vault tokens issued to TFE."
  type        = number
  default     = 1200
}

variable "vault_policy_name" {
  description = "Name of the Vault policy attached to the JWT auth role."
  type        = string
  default     = "tfe-vault-backed-aws-policy"
}

# ─── Vault AWS Secrets Engine ──────────────────────────────────────────────

variable "aws_secrets_backend_path" {
  description = "Mount path for the Vault AWS secrets engine."
  type        = string
  default     = "aws"
}

variable "aws_secrets_backend_region" {
  description = "AWS region the secrets engine uses when calling the STS API."
  type        = string
}

variable "vault_aws_access_key_id" {
  description = "AWS access key ID for the IAM user Vault authenticates as when calling STS. Required when Vault is not running on EC2 with a suitable instance profile."
  type        = string
  sensitive   = true
  default     = ""
}

variable "vault_aws_secret_access_key" {
  description = "AWS secret access key for the IAM user Vault authenticates as when calling STS. Required when vault_aws_access_key_id is set."
  type        = string
  sensitive   = true
  default     = ""
}

variable "aws_secrets_role_name" {
  description = "Name of the Vault AWS secrets engine role."
  type        = string
  default     = "tfe-dynamic-aws-role"
}

variable "default_sts_ttl_seconds" {
  description = "Default TTL for STS credentials generated by Vault."
  type        = number
  default     = 3600 # 1 hour
}

variable "max_sts_ttl_seconds" {
  description = "Maximum TTL for STS credentials generated by Vault."
  type        = number
  default     = 43200 # 12 hours
}

# ─── AWS IAM — Target Role ─────────────────────────────────────────────────
# Vault assumes this IAM role in the target AWS account when generating
# dynamic credentials for TFE.

variable "target_iam_role_name" {
  description = "Name of the AWS IAM role that Vault will assume to generate dynamic credentials."
  type        = string
  default     = "vault-dynamic-creds-target"
}

variable "vault_iam_user_arn" {
  description = "ARN of the IAM principal Vault authenticates as (IAM user ARN when using static credentials, or IAM role ARN when Vault runs on EC2). This principal is granted sts:AssumeRole on the target role."
  type        = string
}

variable "target_iam_policy_json" {
  description = "IAM policy document (JSON) granting the permissions TFE runs will need. Defaults to read-only access for demonstration."
  type        = string
  default     = ""
}

# ─── TFE Workspace Variable Injection ─────────────────────────────────────

variable "tfe_workspace_id" {
  description = "TFE workspace ID to inject environment variables into (e.g. 'ws-XXXXXXXXXXXXXXXX')."
  type        = string
}

variable "vault_ca_cert_b64" {
  description = "Base64-encoded PEM CA certificate for Vault. Injected as TFC_VAULT_ENCODED_CACERT when non-empty for self-signed Vault TLS."
  type        = string
  sensitive   = true
  default     = ""
}

variable "set_vault_auth_vars" {
  description = "When true, sets the generic Vault auth workspace vars for this flow (TFC_VAULT_PROVIDER_AUTH, TFC_VAULT_ADDR, TFC_VAULT_AUTH_PATH, TFC_VAULT_RUN_ROLE, and TFC_VAULT_ENCODED_CACERT when provided). Set to false only if another process writes the same values for this module's jwt_backend_path and vault_role_name."
  type        = bool
  default     = true
}

variable "create_jwt_backend" {
  description = "When true, creates the Vault JWT auth backend at jwt_backend_path. Set to false only when an external module already manages a JWT backend at the same path and you want to reuse it."
  type        = bool
  default     = true
}

variable "tfe_ca_cert_pem" {
  description = "PEM-encoded CA certificate for TFE's self-signed TLS cert. Used for the OIDC discovery CA when create_jwt_backend = true."
  type        = string
  default     = ""
}
