# ─── Vault Connection ──────────────────────────────────────────────────────

variable "vault_addr" {
  description = "Address of the Vault server. Used for TFE workspace variable injection."
  type        = string
}

variable "vault_namespace" {
  description = "Vault namespace. Leave empty for root namespace."
  type        = string
  default     = ""
}

# ─── TFE Identity ──────────────────────────────────────────────────────────

variable "tfe_hostname" {
  description = "Hostname of the self-hosted Terraform Enterprise instance."
  type        = string
}

variable "tfe_organization" {
  description = "TFE organization name used to scope JWT bound_claims."
  type        = string
}

variable "tfe_project" {
  description = "TFE project name. Use '*' to match all projects."
  type        = string
  default     = "*"
}

variable "tfe_workspace" {
  description = "TFE workspace name. Use '*' to match all workspaces in the project."
  type        = string
  default     = "*"
}

# ─── Vault JWT Auth Backend ────────────────────────────────────────────────

variable "jwt_backend_path" {
  description = "Mount path for the JWT auth backend."
  type        = string
  default     = "jwt"
}

variable "vault_role_name" {
  description = "Name of the Vault JWT auth role for TFE workspaces."
  type        = string
  default     = "tfe-vault-backed-aws"
}

variable "workload_identity_audience" {
  description = "Expected 'aud' claim in TFE workload identity tokens."
  type        = string
  default     = "vault.workload.identity"
}

variable "token_ttl_seconds" {
  description = "Lifetime in seconds for Vault tokens issued to TFE."
  type        = number
  default     = 1200
}

variable "vault_policy_name" {
  description = "Name of the Vault policy attached to the JWT auth role."
  type        = string
  default     = "tfe-vault-backed-aws-policy"
}

# ─── Vault AWS Secrets Engine ──────────────────────────────────────────────

variable "aws_secrets_backend_path" {
  description = "Mount path for the Vault AWS secrets engine."
  type        = string
  default     = "aws"
}

variable "aws_secrets_backend_region" {
  description = "AWS region the secrets engine uses when calling the STS API."
  type        = string
}

variable "vault_aws_access_key_id" {
  description = "AWS access key ID for the Vault IAM user. Leave empty to rely on the Vault EC2 instance profile."
  type        = string
  sensitive   = true
  default     = ""
}

variable "vault_aws_secret_access_key" {
  description = "AWS secret access key for the Vault IAM user. Leave empty to rely on the Vault EC2 instance profile."
  type        = string
  sensitive   = true
  default     = ""
}

variable "aws_secrets_role_name" {
  description = "Name of the Vault AWS secrets engine role."
  type        = string
  default     = "tfe-dynamic-aws-role"
}

variable "default_sts_ttl_seconds" {
  description = "Default TTL for STS credentials generated by Vault."
  type        = number
  default     = 3600 # 1 hour
}

variable "max_sts_ttl_seconds" {
  description = "Maximum TTL for STS credentials generated by Vault."
  type        = number
  default     = 43200 # 12 hours
}

# ─── AWS IAM — Target Role ─────────────────────────────────────────────────
# Vault assumes this IAM role in the target AWS account when generating
# dynamic credentials for TFE.

variable "target_iam_role_name" {
  description = "Name of the AWS IAM role that Vault will assume to generate dynamic credentials."
  type        = string
  default     = "vault-dynamic-creds-target"
}

variable "vault_iam_user_arn" {
  description = "ARN of the Vault IAM user (or the Vault EC2 instance role ARN) that is allowed to assume the target IAM role."
  type        = string
}

variable "target_iam_policy_json" {
  description = "IAM policy document (JSON) granting the permissions TFE runs will need. Defaults to read-only access for demonstration."
  type        = string
  default     = ""
}

# ─── TFE Workspace Variable Injection ─────────────────────────────────────

variable "configure_tfe_workspace" {
  description = "When true, create tfe_variable resources to inject vault-backed AWS credential env vars into the target TFE workspace."
  type        = bool
  default     = false
}

variable "tfe_workspace_id" {
  description = "TFE workspace ID. Required when configure_tfe_workspace = true."
  type        = string
  default     = ""
}

variable "vault_ca_cert_b64" {
  description = "Base64-encoded PEM CA certificate for Vault. Injected as TFC_VAULT_ENCODED_CACERT when non-empty."
  type        = string
  sensitive   = true
  default     = ""
}
